Repository lfortran/lfortran, pull requests merged in 2023-11, with the labels that each got.

#2768 Split UpdateArgsVisitor to ArgsVisitor and ArgsReplacer
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/asr_utils.cpp
Labels: SciPy

#2796 Add provision to `visit_FunctionCall` in `update_call_args`
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/asr_utils.cpp
  tests/external_03.f90
  tests/reference/asr-allow_implicit_interface3-7ef92cc.json
  tests/reference/asr-allow_implicit_interface3-7ef92cc.stdout
  tests/reference/asr-external3-2aafcb3.json
  tests/reference/asr-external3-2aafcb3.stdout
  tests/reference/asr-external4-4e8bc7b.json
  tests/reference/asr-external4-4e8bc7b.stdout
  tests/reference/asr-external_01-6754623.json
  tests/reference/asr-external_01-6754623.stdout
  tests/reference/asr-external_03-fe60427.json
  tests/reference/asr-external_03-fe60427.stdout
  tests/tests.toml
Labels: SciPy

#2802 Handle template binary operations with different types
  integration_tests/CMakeLists.txt
  integration_tests/template_03.f90
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  tests/reference/asr-template_03-6afb845.json
  tests/reference/asr-template_03-6afb845.stdout
  tests/tests.toml
Labels: generics

#2804 Manage duplicate wrapper for intrinsic operators in template instantiations
  integration_tests/CMakeLists.txt
  integration_tests/template_travel_01b.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/libasr/pass/instantiate_template.cpp
  src/libasr/pass/instantiate_template.h
  tests/reference/asr-template_02-021cc51.json
  tests/reference/asr-template_02-021cc51.stdout
  tests/reference/asr-template_03-6afb845.json
  tests/reference/asr-template_03-6afb845.stdout
  tests/reference/asr-template_add_01c-a5654a9.json
  tests/reference/asr-template_add_01c-a5654a9.stdout
  tests/reference/asr-template_add_02-1dafc5f.json
  tests/reference/asr-template_add_02-1dafc5f.stdout
  tests/reference/asr-template_add_03-43a00f9.json
  tests/reference/asr-template_add_03-43a00f9.stdout
  tests/reference/asr-template_simple_01-964c12e.json
  tests/reference/asr-template_simple_01-964c12e.stdout
  tests/reference/asr-template_simple_02-35381bd.json
  tests/reference/asr-template_simple_02-35381bd.stdout
  tests/reference/asr-template_simple_03-17a83b7.json
  tests/reference/asr-template_simple_03-17a83b7.stdout
  tests/reference/asr-template_travel_01b-db46a56.json
  tests/reference/asr-template_travel_01b-db46a56.stdout
  tests/tests.toml
Labels: generics

#2800 Handle external interface in `convert_call_args`
  integration_tests/CMakeLists.txt
  integration_tests/external_07.f90
  integration_tests/external_08.f90
  src/libasr/codegen/asr_to_llvm.cpp
  tests/external_04.f90
  tests/reference/llvm-external_03-c3442bb.json
  tests/reference/llvm-external_03-c3442bb.stdout
  tests/reference/llvm-external_04-30bc1c7.json
  tests/reference/llvm-external_04-30bc1c7.stdout
  tests/tests.toml
Labels: SciPy

#2803 Syntax for more expressive types during template instantiations
  grammar/AST.asdl
  integration_tests/CMakeLists.txt
  integration_tests/template_03b.f90
  src/lfortran/parser/parser.yy
  src/lfortran/parser/semantics.h
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  tests/reference/asr-template_02-021cc51.json
  tests/reference/asr-template_02-021cc51.stdout
  tests/reference/ast-template_01-5309b9a.json
  tests/reference/ast-template_01-5309b9a.stdout
  tests/reference/ast-template_02-80b38d0.json
  tests/reference/ast-template_02-80b38d0.stdout
  tests/reference/ast-template_03b-6812e13.json
  tests/reference/ast-template_03b-6812e13.stdout
  tests/reference/ast-template_nested-35ad81a.json
  tests/reference/ast-template_nested-35ad81a.stdout
  tests/reference/ast-template_struct_01-f11e745.json
  tests/reference/ast-template_struct_01-f11e745.stdout
  tests/reference/ast-template_travel_01-7f304df.json
  tests/reference/ast-template_travel_01-7f304df.stdout
  tests/tests.toml
Labels: generics

#2811 CI: test scipy/integrate/quadpack
  .github/workflows/CI.yml
Labels: SciPy

#2822 Add test for the number of values and variables match in DATA
  integration_tests/CMakeLists.txt
  integration_tests/data_11.f90
Labels: SciPy

#2838 Handle symbol import for templates, requirements
  integration_tests/CMakeLists.txt
  integration_tests/template_04.f90
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  tests/reference/asr-template_04-f41dd3e.json
  tests/reference/asr-template_04-f41dd3e.stdout
  tests/tests.toml
Labels: generics

#2149 Added several tests for SciPy
  integration_tests/CMakeLists.txt
  integration_tests/arrays_intrin_07.f90
  integration_tests/capital_01.f90
  integration_tests/procedure_05.f90
  integration_tests/save_04.f90
  integration_tests/save_06.f90
Labels: SciPy

#2865 [ASR Pass] Handle ArraySection and SIMDArray BinOp
  .github/workflows/CI.yml
  ci/test.xsh
  integration_tests/CMakeLists.txt
  integration_tests/run_tests.py
  src/libasr/pass/array_op.cpp
Labels: asr_pass

#2891 [ASR Pass] FMA: Create an IntrinsicScalarFunction for SIMDArray
  integration_tests/CMakeLists.txt
  integration_tests/matmul_01.f90
  src/libasr/codegen/asr_to_c.cpp
  src/libasr/codegen/asr_to_c_cpp.h
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/pass/pass_utils.cpp
  tests/reference/asr-matmul_01-7b0b0c2.json
  tests/reference/asr-matmul_01-7b0b0c2.stdout
Labels: asr_pass

#2912 Apply legacy array sections on arguments of function call
  integration_tests/CMakeLists.txt
  integration_tests/legacy_array_sections_03.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_common_visitor.h
Labels: SciPy
