Repository lfortran/lfortran, pull requests merged in 2023-06, with the labels that each got.

#1731 Add provision to declare non `c_ptr` structs
  integration_tests/CMakeLists.txt
  integration_tests/derived_types_22.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: SciPy

#1738 Handle `dimension_t` in COMMON blocks
  integration_tests/common_06.f90
  src/lfortran/semantics/ast_common_visitor.h
  tests/errors/common1.f90
  tests/reference/asr-common1-bbe229a.json
  tests/reference/asr-common1-bbe229a.stderr
  tests/reference/asr-common_06-4a72d58.json
  tests/reference/asr-common_06-4a72d58.stdout
  tests/tests.toml
Labels: SciPy

#1586 clarify Variable.md
  doc/src/asr/asr_nodes/symbol_nodes/Variable.md
Labels: ready for review

#1754 Bug fixes towards COMMON block
  integration_tests/CMakeLists.txt
  integration_tests/common_07.f90
  integration_tests/common_08.f90
  integration_tests/common_09.f90
  src/lfortran/semantics/ast_common_visitor.h
Labels: SciPy

#1763 Allow struct instance member in data stmts
  integration_tests/CMakeLists.txt
  integration_tests/data_06.f90
  integration_tests/data_07.f90
  src/lfortran/semantics/ast_common_visitor.h
Labels: SciPy

#1794 Bug fixes for `statement` functions
  integration_tests/CMakeLists.txt
  integration_tests/statement_01.f90
  integration_tests/statement_02.f90
  integration_tests/statement_03.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_common_visitor.h
  tests/reference/asr-statement_01-00eefc8.json
  tests/reference/asr-statement_01-00eefc8.stdout
  tests/reference/asr-statement_02-daaef34.json
  tests/reference/asr-statement_02-daaef34.stdout
  tests/reference/asr-statement_03-99c9cd3.json
  tests/reference/asr-statement_03-99c9cd3.stdout
  tests/tests.toml
Labels: SciPy

#1789 Add provision to handle `external` declaration
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/lfortran/semantics/ast_to_asr.cpp
  tests/errors/implicit_typing4.f90
  tests/external1.f90
  tests/external2.f90
  tests/reference/asr-allow_implicit_interface-68156ec.json
  tests/reference/asr-allow_implicit_interface-68156ec.stdout
  tests/reference/asr-allow_implicit_interface3-7ef92cc.json
  tests/reference/asr-allow_implicit_interface3-7ef92cc.stdout
  tests/reference/asr-external1-5568fec.json
  tests/reference/asr-external1-5568fec.stdout
  tests/reference/asr-external2-e21d7a5.json
  tests/reference/asr-external2-e21d7a5.stdout
  tests/reference/asr-implicit_typing4-df7d614.json
  tests/reference/asr-implicit_typing4-df7d614.stderr
  tests/tests.toml
Labels: SciPy

#1792 Add provision to update args of subroutine call when `--implicit-interface` is enabled
  src/lfortran/semantics/ast_body_visitor.cpp
  tests/allow_implicit_interface4.f90
  tests/reference/asr-allow_implicit_interface4-4615450.json
  tests/reference/asr-allow_implicit_interface4-4615450.stdout
  tests/tests.toml
Labels: SciPy

#1802 handle `implicit none` in external variable declaration
  integration_tests/CMakeLists.txt
  integration_tests/external_02.f90
  src/lfortran/semantics/ast_common_visitor.h
Labels: SciPy

#1800 Handle update of external symbol not present in current scope
  src/lfortran/semantics/ast_common_visitor.h
  tests/external3.f90
  tests/reference/asr-external3-2aafcb3.json
  tests/reference/asr-external3-2aafcb3.stdout
  tests/tests.toml
Labels: SciPy

#1832 Resolved issue #1778 and #1779
  integration_tests/CMakeLists.txt
  integration_tests/template_01.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/libasr/ASR.asdl
  tests/reference/asr-template_01-4f69d5d.json
  tests/reference/asr-template_01-4f69d5d.stdout
  tests/reference/asr-template_add_01-56d8eff.json
  tests/reference/asr-template_add_01-56d8eff.stdout
  tests/reference/asr-template_add_02-1dafc5f.json
  tests/reference/asr-template_add_02-1dafc5f.stdout
  tests/reference/asr-template_add_03-43a00f9.json
  tests/reference/asr-template_add_03-43a00f9.stdout
  tests/reference/asr-template_array_01-691b151.json
  tests/reference/asr-template_array_01-691b151.stdout
  tests/reference/asr-template_array_02-85b6b2e.json
  tests/reference/asr-template_array_02-85b6b2e.stdout
  tests/reference/asr-template_array_03-b7f9799.json
  tests/reference/asr-template_array_03-b7f9799.stdout
  tests/reference/asr-template_array_04-ed63449.json
  tests/reference/asr-template_array_04-ed63449.stdout
  tests/reference/asr-template_nested-5858841.json
  tests/reference/asr-template_nested-5858841.stdout
  tests/reference/asr-template_travel-453a557.json
  tests/reference/asr-template_travel-453a557.stdout
  tests/reference/asr-template_triple-54fa485.json
  tests/reference/asr-template_triple-54fa485.stdout
  tests/reference/ast-template_01-5309b9a.json
  tests/reference/ast-template_01-5309b9a.stdout
  tests/tests.toml
Labels: generics

#1837 Implement `DataImpliedDo`
  integration_tests/CMakeLists.txt
  integration_tests/data_implied_do_01.f90
  integration_tests/data_implied_do_02.f90
  integration_tests/data_implied_do_03.f90
  integration_tests/data_implied_do_04.f90
  src/lfortran/semantics/ast_common_visitor.h
  tests/reference/asr-data_implied_do_01-737a2b1.json
  tests/reference/asr-data_implied_do_01-737a2b1.stdout
  tests/tests.toml
Labels: SciPy

#1835 Implement `SAVE` attribute
  integration_tests/CMakeLists.txt
  integration_tests/save_01.f90
  integration_tests/save_02.f90
  integration_tests/save_03.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  tests/reference/asr-save2-63c8bcc.json
  tests/reference/asr-save2-63c8bcc.stderr
  tests/reference/asr-save2-63c8bcc.stdout
  tests/reference/asr-save_03-1103dd0.json
  tests/reference/asr-save_03-1103dd0.stdout
  tests/save2.f90
  tests/tests.toml
Labels: SciPy

#1841 Allow provision for multiple calls to external procedure
  integration_tests/CMakeLists.txt
  integration_tests/external_05.f90
  integration_tests/external_06.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/lfortran/semantics/ast_to_asr.cpp
  tests/errors/external1.f90
  tests/reference/asr-external1-93d8653.json
  tests/reference/asr-external1-93d8653.stdout
  tests/reference/asr-external1-e4cf9f2.json
  tests/reference/asr-external1-e4cf9f2.stderr
  tests/tests.toml
Labels: SciPy

#1866 Implement `visit_Entry()`
  integration_tests/CMakeLists.txt
  integration_tests/entry_01.f90
  integration_tests/entry_02.f90
  integration_tests/entry_03.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_common_visitor.h
  tests/entry1.f90
  tests/reference/asr-entry1-3075e81.json
  tests/reference/asr-entry1-3075e81.stdout
  tests/reference/asr-entry_02-b8ee2e2.json
  tests/reference/asr-entry_02-b8ee2e2.stdout
  tests/reference/ast-entry1-5b02d99.json
  tests/reference/ast-entry1-5b02d99.stdout
  tests/reference/ast_f90-entry1-5f14c6d.json
  tests/reference/ast_f90-entry1-5f14c6d.stdout
  tests/tests.toml
Labels: SciPy

#1889 Add provision for handling external subroutine
  src/lfortran/semantics/ast_common_visitor.h
  tests/external5.f90
  tests/reference/asr-external5-1198a6f.json
  tests/reference/asr-external5-1198a6f.stdout
  tests/tests.toml
Labels: SciPy

#1894 Add provision to update dependency of entry points
  src/lfortran/semantics/ast_body_visitor.cpp
  tests/entry2.f90
  tests/reference/asr-entry2-a9679e0.json
  tests/reference/asr-entry2-a9679e0.stdout
  tests/tests.toml
Labels: SciPy

#1893 Add provision to check `array->m_type` in data stmt
  integration_tests/CMakeLists.txt
  integration_tests/data_08.f90
  src/lfortran/semantics/ast_common_visitor.h
  tests/reference/asr-implicit4-704272e.json
  tests/reference/asr-implicit4-704272e.stdout
Labels: SciPy

#1762 Implementation of max0() using IntrinsicFunction
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_54.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/pass/intrinsic_function_registry.h
  tests/reference/asr-intrinsic_implicit-77de888.json
  tests/reference/asr-intrinsic_implicit-77de888.stdout
Labels: SciPy
