Repository lfortran/lfortran, pull requests merged in 2024-01, with the labels that each got.

#3024 Support for OverloadedStringConcat and bug fixes
  integration_tests/CMakeLists.txt
  integration_tests/operator_overloading_02.f90
  integration_tests/string_30.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_common_visitor.h
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/libasr/ASR.asdl
  src/libasr/asr_utils.cpp
  src/libasr/asr_utils.h
  src/libasr/asr_verify.cpp
  src/libasr/serialization.cpp
  tests/reference/asr-derived_types_07-c5a29e3.json
  tests/reference/asr-derived_types_07-c5a29e3.stdout
  tests/reference/asr-interface_01-9dc98da.json
  tests/reference/asr-interface_01-9dc98da.stdout
  tests/reference/asr-interface_04-9570e2b.json
  tests/reference/asr-interface_04-9570e2b.stdout
  tests/reference/asr-interface_05-5639d22.json
  tests/reference/asr-interface_05-5639d22.stdout
  tests/reference/asr-modules4-22712cd.json
  tests/reference/asr-modules4-22712cd.stdout
  tests/reference/asr-modules_27-4f64cb2.json
  tests/reference/asr-modules_27-4f64cb2.stdout
  tests/reference/asr-modules_52-5261d38.json
  tests/reference/asr-modules_52-5261d38.stdout
  tests/reference/asr-operator_overloading_02-6076a0f.json
  tests/reference/asr-string2-3425046.json
  tests/reference/asr-string2-3425046.stdout
  tests/reference/asr-subroutines_09-83ddd2b.json
  tests/reference/asr-subroutines_09-83ddd2b.stdout
  tests/reference/llvm-operator_overloading_02-adb886e.json
Labels: stdlib

#3025 Fixes for external symbols
  integration_tests/CMakeLists.txt
  integration_tests/modules_55.f90
  integration_tests/submodule_02.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/asdl_cpp.py
  src/libasr/asr_utils.h
  tests/reference/asr-submodule_02-9152b7b.json
  tests/reference/asr-submodule_02-9152b7b.stdout
Labels: stdlib

#3002 Support other integer kinds in the mod intrinsic
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_100.f90
  src/libasr/pass/intrinsic_function_registry.h
Labels: stdlib

#3017 FIX: Complex im, re is not supported yet for assignment
  integration_tests/CMakeLists.txt
  integration_tests/complex_16.f90
  src/lfortran/semantics/ast_body_visitor.cpp
Labels: stdlib

#3036 CI: test example of stdlib special functions gamma
  .github/workflows/CI.yml
Labels: CI, stdlib

#3032 Add gamma to IntrinsicScalarFunction
  src/lfortran/semantics/comptime_eval.h
  src/libasr/pass/intrinsic_function_registry.h
  src/runtime/impure/lfortran_intrinsic_math.f90
Labels: stdlib

#3045 ci: update stdlib branch to remove workaround for gamma
  .github/workflows/CI.yml
Labels: CI, stdlib

#3059 FIX: Type mismatch in array initializer r32 and i32
  integration_tests/CMakeLists.txt
  integration_tests/arrays_35.f90
  src/lfortran/semantics/ast_common_visitor.h
Labels: stdlib

#3061 FIX: operands to a binary operator are not of the same type!
  integration_tests/CMakeLists.txt
  integration_tests/binop_01.f90
  src/libasr/codegen/llvm_array_utils.cpp
Labels: stdlib

#3075 Fix use of keyword args for intrinsic functions
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_106.f90
  src/lfortran/semantics/ast_common_visitor.h
Labels: stdlib

#3181 FIX: optional argument handling for elemental funtion
  integration_tests/CMakeLists.txt
  integration_tests/elemental_02.f90
  src/libasr/pass/array_op.cpp
Labels: stdlib

#3197 FIX: abs for complex arrays
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_129.f90
  src/libasr/pass/array_op.cpp
  src/libasr/pass/intrinsic_function_registry.h
Labels: stdlib

#3147 Importing issues with requirements and templates
  integration_tests/CMakeLists.txt
  integration_tests/template_01.f90
  integration_tests/template_04.f90
  integration_tests/template_05.f90
  integration_tests/template_array_01.f90
  integration_tests/template_array_01b.f90
  integration_tests/template_array_02.f90
  integration_tests/template_array_02b.f90
  integration_tests/template_field.f90
  integration_tests/template_matrix.f90
  integration_tests/template_matrix_01.f90
  integration_tests/template_matrix_integer.f90
  integration_tests/template_matrix_real.f90
  integration_tests/template_monoid.f90
  integration_tests/template_semigroup.f90
  integration_tests/template_semiring.f90
  integration_tests/template_simple_04.f90
  integration_tests/template_sort_01.f90
  integration_tests/template_struct_01.f90
  integration_tests/template_unitring.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/libasr/asr_utils.h
  src/libasr/modfile.cpp
  src/libasr/pass/instantiate_template.cpp
  src/libasr/serialization.cpp
  tests/reference/asr-template_01-4f69d5d.json
  tests/reference/asr-template_01-4f69d5d.stdout
  tests/reference/asr-template_04-f41dd3e.json
  tests/reference/asr-template_04-f41dd3e.stdout
  tests/reference/asr-template_05-fe28e11.json
  tests/reference/asr-template_05-fe28e11.stdout
  tests/reference/asr-template_array_01-691b151.json
  tests/reference/asr-template_array_01-691b151.stdout
  tests/reference/asr-template_array_01b-98829ac.json
  tests/reference/asr-template_array_01b-98829ac.stdout
  tests/reference/asr-template_array_02-85b6b2e.json
  tests/reference/asr-template_array_02-85b6b2e.stdout
  tests/reference/asr-template_array_02b-fd32c6a.json
  tests/reference/asr-template_array_02b-fd32c6a.stdout
  tests/reference/asr-template_matrix_01-65b17ae.json
  tests/reference/asr-template_matrix_01-65b17ae.stdout
  tests/reference/asr-template_simple_04-951e966.json
  tests/reference/asr-template_simple_04-951e966.stdout
  tests/reference/asr-template_sort_01-b412f73.json
  tests/reference/asr-template_sort_01-b412f73.stdout
  tests/reference/asr-template_struct_01-c320d7d.json
  tests/reference/asr-template_struct_01-c320d7d.stdout
  tests/reference/ast-template_01-5309b9a.json
  tests/reference/ast-template_01-5309b9a.stdout
  tests/reference/ast-template_struct_01-f11e745.json
  tests/reference/ast-template_struct_01-f11e745.stdout
  tests/tests.toml
Labels: generics

#3206 Correctly handle elemental function return variable type
  integration_tests/CMakeLists.txt
  integration_tests/elemental_04.f90
  src/libasr/pass/array_op.cpp
Labels: stdlib

#3265 ASR Verify: visit function signature
  integration_tests/CMakeLists.txt
  integration_tests/arrays_38.f90
  src/libasr/asr_verify.cpp
Labels: stdlib
