Repository lfortran/lfortran, pull requests merged in 2024-02, with the labels that each got.

#3276 ENH: Handle complex constructor over array
  integration_tests/CMakeLists.txt
  integration_tests/complex_17.f90
  src/libasr/pass/array_op.cpp
  src/libasr/pass/pass_utils.cpp
Labels: stdlib

#3298 FIX: incorrect handling of memory allocation / freeing in blocks
  integration_tests/CMakeLists.txt
  integration_tests/block_08.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: stdlib

#3318 Fix: using lfortran intrinsic module inside module
  integration_tests/CMakeLists.txt
  integration_tests/modules_56.f90
  src/lfortran/semantics/ast_symboltable_visitor.cpp
Labels: stdlib

#3339 CI: update test stdlib special function
  .github/workflows/CI.yml
Labels: CI, stdlib

#3381 CI: setup for `stdlib_linalg`
  .github/workflows/CI.yml
Labels: CI, stdlib

#3387 [stdlib] Use source directory as module path directory
  .github/workflows/CI.yml
Labels: stdlib

#3407 Implement `function_call_in_declaration` pass
  integration_tests/CMakeLists.txt
  integration_tests/functions_19.f90
  src/libasr/CMakeLists.txt
  src/libasr/pass/function_call_in_declaration.cpp
  src/libasr/pass/pass_manager.h
  src/libasr/pass/replace_function_call_in_declaration.h
Labels: asr_pass, stdlib

#3415 ENH: support `IntegerBinOp` in pass `function_call_in_declaration`
  integration_tests/CMakeLists.txt
  integration_tests/functions_20.f90
  src/libasr/gen_pass.py
  src/libasr/pass/function_call_in_declaration.cpp
Labels: stdlib

#3464 DEV: implement intrinsic `pack`
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_147.f90
  integration_tests/intrinsics_148.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/asr_utils.h
  src/libasr/codegen/asr_to_fortran.cpp
  src/libasr/pass/intrinsic_array_function_registry.h
  src/libasr/pass/pass_utils.cpp
  src/libasr/pass/pass_utils.h
  tests/reference/asr-array_01_pack-6c829d9.json
  tests/reference/asr-array_01_pack-6c829d9.stdout
  tests/reference/asr-array_02_pack-233bae0.json
  tests/reference/asr-array_02_pack-233bae0.stdout
  tests/reference/asr-modules_43-d01691f.json
  tests/reference/asr-modules_43-d01691f.stdout
  tests/reference/pass_array_op-modules_43-6930881.json
  tests/reference/pass_array_op-modules_43-6930881.stdout
Labels: stdlib

#3484 DEV: implement intrinsic `unpack`
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_149.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/pass/intrinsic_array_function_registry.h
  src/libasr/pass/pass_utils.cpp
  src/libasr/pass/pass_utils.h
Labels: stdlib

#3495 CI: test `stdlib/linalg`
  .github/workflows/CI.yml
Labels: CI, stdlib

#3532 ENH: Support complex type for `matmul`
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_159.f90
  src/libasr/asr_builder.h
  src/libasr/pass/intrinsic_array_function_registry.h
  tests/reference/asr-matrix_matmul_03-a99cdd1.json
  tests/reference/asr-matrix_matmul_03-a99cdd1.stderr
Labels: stdlib

#3519 FIX: Missing dependency in ASR
  integration_tests/CMakeLists.txt
  integration_tests/functions_21.f90
  integration_tests/functions_22.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/asr_utils.h
  src/libasr/asr_verify.cpp
  src/libasr/pass/function_call_in_declaration.cpp
  src/libasr/pass/pass_utils.h
Labels: stdlib
