Repository lfortran/lfortran, pull requests merged in 2025-06, with the labels that each got.

#7535 fix: correct `Struct` name order in `visit_arrayitem` and CreateLoad for nested SIM
  integration_tests/CMakeLists.txt
  integration_tests/class_30.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: toml-f

#7531 fix : Do not call Deepcopy in LLVM for unlimited polymorphic variable (abstract_type)
  integration_tests/CMakeLists.txt
  integration_tests/class_28.f90
  src/libasr/codegen/llvm_utils.cpp
Labels: stdlib

#7527 fix: get type pointer for classes in `associated` and `allocated` intrinsics
  integration_tests/CMakeLists.txt
  integration_tests/class_29.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: toml-f

#7557 enh: support more ES format test cases
  integration_tests/format_30.f90
  src/libasr/runtime/lfortran_intrinsics.c
  tests/reference/run-format_30-3cec484.json
  tests/reference/run-format_30-3cec484.stdout
Labels: format

#7567 CI: fix debugging info about github group
  .github/workflows/CI.yml
Labels: CI

#7597 ci: setup `splpak`
  ci/test_third_party_codes.sh
Labels: CI

#7610 CI: remove usage of xonsh and remove unused environment files
  .github/workflows/CI.yml
  azure-pipelines.yml
  ci/azure_install_macos.sh
  ci/build.sh
  ci/build.xsh
  ci/environment_docs_linux.yml
  ci/environment_linux.yml
  ci/environment_linux_llvm.yml
  pixi.toml
Labels: CI

#7634 fix: handle class pointer passed/returned in function
  integration_tests/class_21.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: toml-f

#7638 [OPENMP] FEAT: Implement Single/Master Construct
  integration_tests/CMakeLists.txt
  integration_tests/openmp_48.f90
  integration_tests/openmp_49.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/libasr/ASR.asdl
  src/libasr/pass/openmp.cpp
Labels: openmp

#7643 fix: inconsistent casting bugs in LLVM IR generation
  integration_tests/CMakeLists.txt
  integration_tests/transfer_03.f90
  integration_tests/transfer_04.f90
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/codegen/llvm_array_utils.cpp
  src/libasr/pass/pass_array_by_data.cpp
Labels: separate compilation

#7711 enh: support subroutine conversion StructType pointer returning function
  integration_tests/class_51.f90
  src/libasr/pass/subroutine_from_function.cpp
Labels: toml-f

#7717 ci: test toml-f, jonquil build
  ci/test_third_party_codes.sh
Labels: CI, toml-f, jonquil

#7746 ci: enable testing of more examples for stdlib_stringlist_type
  ci/test_third_party_codes.sh
Labels: CI, stdlib

#7781 feat: introduce and implement label in `Select`
  integration_tests/CMakeLists.txt
  integration_tests/select_label_01.f90
  src/lfortran/semantics/ast_body_visitor.cpp
  src/libasr/ASR.asdl
  src/libasr/pass/select_case.cpp
  tests/reference/asr-assign_to1-a6b7599.json
  tests/reference/asr-assign_to1-a6b7599.stdout
  tests/reference/asr-assign_to2-127a642.json
  tests/reference/asr-assign_to2-127a642.stdout
  tests/reference/asr-case_01-b59db9c.json
  tests/reference/asr-case_01-b59db9c.stdout
  tests/reference/asr-case_02-8557909.json
  tests/reference/asr-case_02-8557909.stdout
  tests/reference/asr-case_03-e03f722.json
  tests/reference/asr-case_03-e03f722.stdout
  tests/reference/asr-case_05-8f778ac.json
  tests/reference/asr-case_05-8f778ac.stdout
  tests/reference/asr-case_06-f84222d.json
  tests/reference/asr-case_06-f84222d.stdout
  tests/reference/asr-common_05-f767179.json
  tests/reference/asr-common_05-f767179.stdout
  tests/reference/asr-fixed_form_goto_select-a0c3483.json
  tests/reference/asr-fixed_form_goto_select-a0c3483.stdout
  tests/reference/asr-goto_04-2487215.json
  tests/reference/asr-goto_04-2487215.stdout
  tests/reference/pass_dead_code_removal-case_06-e7f007f.json
  tests/reference/pass_dead_code_removal-case_06-e7f007f.stdout
Labels: MCLI2

#7803 fix: creating helper function while having function call in declaration with logical not
  integration_tests/CMakeLists.txt
  integration_tests/arrays_93.f90
  src/libasr/pass/function_call_in_declaration.cpp
Labels: stdlib

#7817 enh: populate all intrinsic op types in hashmap
  integration_tests/CMakeLists.txt
  integration_tests/operator_overloading_12.f90
  src/lfortran/semantics/ast_common_visitor.h
Labels: BerkeleyLab/julienne

#7821 feat: introduce `c_intptr_t` in `iso_c_binding`
  integration_tests/iso_c_binding_01.f90
  src/runtime/pure/lfortran_intrinsic_iso_c_binding.f90
  tests/reference/asr-c_ptr_02-fce1b0e.json
  tests/reference/asr-c_ptr_02-fce1b0e.stdout
Labels: BerkeleyLab/julienne

#7826 CI: Enable test for logger & remove all workaround of array
  ci/test_third_party_codes.sh
Labels: CI, stdlib

#7824 fix: lower `remote_sym` name before checking it in symbol table
  integration_tests/CMakeLists.txt
  integration_tests/operator_overloading_13.f90
  src/lfortran/semantics/ast_symboltable_visitor.cpp
Labels: BerkeleyLab/julienne

#7894 feat: introduce `common` linkage for global vars in separate compilation
  integration_tests/CMakeLists.txt
  integration_tests/separate_compilation_14.f90
  integration_tests/separate_compilation_14a.f90
  integration_tests/separate_compilation_15.f90
  integration_tests/separate_compilation_15a.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: PRIMA, separate compilation
