Repository lfortran/lfortran, pull requests merged in 2025-03, with the labels that each got.

#6465 enh: add fortran labels for tests working with fortran backend
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_fortran.cpp
Labels: Fortran

#6567 CI: use branch for POT3D with much simplier git history
  .github/workflows/CI.yml
Labels: CI, POT3D

#6738 fix: handle return_var correctly for `findloc` intrinsic
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_370.f90
  src/libasr/pass/intrinsic_array_function_registry.h
Labels: intrinsic, AoC-2024

#6740 CI: use the commit of pot3d branch which exits with non-zero status on validation failure
  .github/workflows/CI.yml
Labels: POT3D

#6765 fix: don't assign back `intent(in)` variables in nested_vars
  integration_tests/CMakeLists.txt
  integration_tests/nested_vars3.f90
  src/libasr/pass/nested_vars.cpp
Labels: stdlib

#6751 fix: handle optional keyword args correctly for class procedure
  integration_tests/CMakeLists.txt
  integration_tests/class_15.f90
  src/lfortran/semantics/ast_common_visitor.h
  tests/errors/continue_compilation_1.f90
  tests/reference/asr-continue_compilation_1-04b6d40.json
  tests/reference/asr-continue_compilation_1-04b6d40.stderr
Labels: stdlib
