Repository lfortran/lfortran, pull requests merged in 2025-05, with the labels that each got.

#7116 ci: bump to latest stdlib commit with bitsets
  ci/test_third_party_codes.sh
Labels: CI, stdlib

#7124 fix: handle different kinds in `ishft` intrinsic
  integration_tests/intrinsics_130.f90
  src/libasr/pass/intrinsic_functions.h
Labels: stdlib

#7125 fix: handle different kind in `select case` expr
  integration_tests/case_01.f90
  src/libasr/pass/pass_utils.cpp
  tests/reference/asr-case_01-b59db9c.json
  tests/reference/asr-case_01-b59db9c.stdout
  tests/reference/ast-case_01-929583e.json
  tests/reference/ast-case_01-929583e.stdout
  tests/reference/ast_f90-case_01-dcc012a.json
  tests/reference/ast_f90-case_01-dcc012a.stdout
  tests/reference/c-case_01-2ff47e6.json
  tests/reference/c-case_01-2ff47e6.stdout
  tests/reference/cpp-case_01-49038b7.json
  tests/reference/cpp-case_01-49038b7.stdout
  tests/reference/julia-case_01-cbdd0aa.json
  tests/reference/julia-case_01-cbdd0aa.stdout
  tests/reference/llvm-case_01-09dad75.json
  tests/reference/llvm-case_01-09dad75.stdout
Labels: stdlib

#7155 ci: update stdlib ci for `io` package
  ci/test_third_party_codes.sh
Labels: CI, stdlib

#7160 fix: handle `PointerToDataArray` in `fileRead`
  integration_tests/file_26.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: stdlib

#7165 enh: handling of intrinsic modules in separate compilation
  ci/test_third_party_codes.sh
  integration_tests/CMakeLists.txt
  integration_tests/separate_compilation_05.f90
  integration_tests/separate_compilation_05a.f90
  integration_tests/separate_compilation_05b.f90
  src/bin/lfortran.cpp
  src/bin/lfortran_command_line_parser.cpp
  src/libasr/asr_scopes.cpp
  src/libasr/asr_utils.cpp
  src/libasr/pass/unique_symbols.cpp
  src/libasr/utils.h
Labels: separate compilation

#7190 fix: Handle different kinds in `ArraySection` inside intrinsic
  integration_tests/array_04_transfer.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/pass/array_struct_temporary.cpp
Labels: stdlib

#7339 ci: setup fastGPT with separate compilation
  ci/test_third_party_codes.sh
Labels: separate compilation

#7341 enh: enable more integration tests
  integration_tests/CMakeLists.txt
  src/libasr/codegen/asr_to_llvm.cpp
Labels: separate compilation

#7364 ref: remove `parserError` class from file `parser_exception.h`
  src/lfortran/parser/parser_exception.h
Labels: error resiliency

#7379 ci: update hash for stringlist package
  ci/test_third_party_codes.sh
Labels: stdlib

#7381 enh: handling of call arguments in case of specified intent
  ci/test_third_party_codes.sh
  integration_tests/CMakeLists.txt
  integration_tests/intent_03.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: separate compilation

#7429 fix: correct `m_original_name` for structs in nested pass
  integration_tests/CMakeLists.txt
  integration_tests/nested_12.f90
  src/libasr/pass/nested_vars.cpp
Labels: toml-f

#7483 enh: support reading int16 array and integers
  integration_tests/CMakeLists.txt
  integration_tests/file_31.f90
  integration_tests/file_31_data.txt
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/runtime/lfortran_intrinsics.c
  src/libasr/runtime/lfortran_intrinsics.h
Labels: separate compilation

#7449 [OPENMP] Feat: Introduce OMPRegion Node in ASR and Represent Sections Construct in ASR
  integration_tests/openmp_44.f90
  integration_tests/openmp_45.f90
  integration_tests/openmp_46.f90
  src/lfortran/parser/semantics.h
  src/lfortran/semantics/ast_body_visitor.cpp
  src/libasr/ASR.asdl
  tests/reference/asr_openmp-openmp_44-1c0f6fe.json
  tests/reference/asr_openmp-openmp_44-1c0f6fe.stdout
  tests/reference/asr_openmp-openmp_45-1c0e790.json
  tests/reference/asr_openmp-openmp_45-1c0e790.stdout
  tests/reference/asr_openmp-openmp_46-1b93fa8.json
  tests/reference/asr_openmp-openmp_46-1b93fa8.stdout
  tests/tests.toml
Labels: openmp

#7503 fix: allow struct to class association if struct is extended type
  integration_tests/CMakeLists.txt
  integration_tests/class_27.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: toml-f

#7507 CI: club LSP tests with our existing CI tests of macOS / Linux
  .github/workflows/CI.yml
Labels: CI
