Repository lfortran/lfortran, pull requests merged in 2025-02, with the labels that each got.

#6207 enh: support `values` in date_and_time intrinsic
  integration_tests/intrinsics_39.f90
  src/libasr/pass/intrinsic_subroutines.h
  src/libasr/runtime/lfortran_intrinsics.c
  src/libasr/runtime/lfortran_intrinsics.h
  tests/reference/asr-intrinsics_39-f721e16.json
Labels: intrinsic, PRIMA

#6209 fix: consider only `intent(in)` scalar argument while creating dimension for temporary
  integration_tests/functions_32.f90
  src/libasr/asr_utils.h
  tests/reference/asr-template_04-f41dd3e.json
  tests/reference/asr-template_04-f41dd3e.stdout
  tests/reference/asr-template_array_05-ae2710a.json
  tests/reference/asr-template_array_05-ae2710a.stdout
  tests/reference/asr-template_matrix_01-65b17ae.json
  tests/reference/asr-template_matrix_01-65b17ae.stdout
Labels: PRIMA

#6212 CI: update PRIMA CI (Removed Workarounds)
  .github/workflows/CI.yml
Labels: CI, PRIMA

#6236 feat: add support for Struct procedure Variables in `pass_array_by_data`
  integration_tests/CMakeLists.txt
  integration_tests/derived_types_40.f90
  src/libasr/pass/pass_array_by_data.cpp
Labels: tests, PRIMA

#6246 fix: create load when associate value is Struct procedure Member
  integration_tests/derived_types_40.f90
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/pass/pass_array_by_data.cpp
Labels: tests, PRIMA

#6247 enh: `function_call_in_declaration` pass to be generic and supporting BinOp
  integration_tests/CMakeLists.txt
  integration_tests/arrays_10_size.f90
  integration_tests/arrays_11_size.f90
  integration_tests/arrays_12_size.f90
  src/libasr/pass/function_call_in_declaration.cpp
Labels: PRIMA

#6263 enh: Support ExternalSymbols in function_call_in_declaration pass
  integration_tests/arrays_10_size.f90
  src/libasr/pass/function_call_in_declaration.cpp
Labels: PRIMA

#6272 enh: support negative vars in `function_call_in declaration`
  integration_tests/arrays_10_size.f90
  src/libasr/pass/function_call_in_declaration.cpp
Labels: PRIMA

#6275 ci: update PRIMA CI (Removed Workarounds)
  .github/workflows/CI.yml
Labels: CI, PRIMA

#6319 fix: handle compile time values correctly in `pack` intrinsic
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_359.f90
  src/libasr/pass/intrinsic_array_function_registry.h
Labels: intrinsic

#6306 Refactor `Sign_from_value` pass
  integration_tests/sign_from_value.f90
  src/libasr/pass/sign_from_value.cpp
  tests/reference/asr-sign_from_value-b974070.json
  tests/reference/asr-sign_from_value-b974070.stdout
  tests/reference/pass_sign_from_value-sign_from_value-ba1c944.json
  tests/reference/pass_sign_from_value-sign_from_value-ba1c944.stdout
Labels: --fast

#6403 ci: remove PRIMA workarounds
  .github/workflows/CI.yml
Labels: PRIMA

#6404 enh: Support FunctionCall in descriptor temporary pass
  integration_tests/array_section_04.f90
  src/lfortran/semantics/ast_common_visitor.h
  src/libasr/pass/array_passed_in_function_call.cpp
Labels: PRIMA

#6410 ci: test new `prima` branch with less workarounds
  .github/workflows/CI.yml
Labels: PRIMA

#6413 ci: use latest hash with removed workaround for prima
  .github/workflows/CI.yml
Labels: CI, PRIMA

#6426 ci: switch OS for prima tests
  .github/workflows/CI.yml
Labels: CI, PRIMA

#6439 Fix: Handle external symbol in nullify and update prima CI
  .github/workflows/CI.yml
  integration_tests/CMakeLists.txt
  integration_tests/nullify_05.f90
  src/libasr/codegen/asr_to_fortran.cpp
  src/libasr/codegen/asr_to_llvm.cpp
Labels: tests, PRIMA
