Repository lfortran/lfortran, pull requests merged in 2025-01, with the labels that each got.

#5881 docs: include dependency for source tarball installation and fix `cd` command
  doc/src/installation.md
Labels: documentation

#5884 fix :Visit internals of the symbol instead of passing it if it's identified as classProcedure
  integration_tests/CMakeLists.txt
  integration_tests/pass_array_by_data_09.f90
  src/libasr/pass/pass_array_by_data.cpp
Labels: AoC-2023

#5908 Add test for to check array `mask` arg of `any` intrinsic
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_336.f90
  src/libasr/codegen/asr_to_fortran.cpp
Labels: Fortran

#5894 build: handle stacktraces before setting `LFORTRAN_LLVM_COMPONENTS`
  .github/workflows/CI.yml
  CMakeLists.txt
Labels: build

#5915 enh: add support for passing argument of any type to a polymorphic function parameter
  integration_tests/CMakeLists.txt
  integration_tests/polymorphic_arguments_01.f90
  integration_tests/polymorphic_arguments_02.f90
  src/lfortran/semantics/ast_symboltable_visitor.cpp
  src/libasr/asr_utils.h
  tests/reference/asr-polymorphic_arguments_02-bb6f3e2.json
  tests/reference/asr-polymorphic_arguments_02-bb6f3e2.stdout
  tests/tests.toml
Labels: fman

#5919 fix: handling of nested pass array by data functions
  integration_tests/CMakeLists.txt
  integration_tests/pass_array_by_data_10.f90
  src/libasr/pass/pass_array_by_data.cpp
Labels: PRIMA

#5956 tests: uncomments tests and remove TODO
  integration_tests/CMakeLists.txt
Labels: tests

#5983 ci: resolve failures
  .github/workflows/CI.yml
  ci/environment_linux.yml
  ci/test_cpp_version.xsh
  ci/test_without_llvm_backend.xsh
  environment_linux.yml
  integration_tests/CMakeLists.txt
  integration_tests/format_04.f90
Labels: build

#6000 ci: test compilation of `examples/project3`
  .github/workflows/CI.yml
Labels: CI, tests

#5968 refactor: perform scoped duplication of function body and arguments while duplicating `ASR::Function_t`
  src/libasr/asr_utils.h
Labels: refactor

#6012 fix: handle allocatable arrays with spread
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_342.f90
  src/libasr/intrinsic_func_registry_util_gen.py
  src/libasr/pass/intrinsic_array_function_registry.h
Labels: intrinsic

#6014 fix: throw error for non scalar args in or/and/xor and non scalar kind arg
  src/lfortran/semantics/ast_common_visitor.h
  tests/errors/continue_compilation_1.f90
  tests/reference/asr-continue_compilation_1-04b6d40.json
  tests/reference/asr-continue_compilation_1-04b6d40.stderr
  tests/reference/asr-continue_compilation_2-a6145a1.json
  tests/reference/asr-continue_compilation_2-a6145a1.stderr
  tests/reference/asr-int_01-9bf3eb9.json
  tests/reference/asr-int_01-9bf3eb9.stderr
  tests/reference/asr-kind_01-6c675be.json
  tests/reference/asr-kind_01-6c675be.stderr
Labels: intrinsic

#6042 tests: add `NOFAST` label for test `pass_array_by_data_05.f90`
  integration_tests/CMakeLists.txt
Labels: tests

#6041 fix: throw error for non-scalar in repeat intrinsic
  src/lfortran/semantics/ast_common_visitor.h
  tests/errors/continue_compilation_1.f90
  tests/reference/asr-continue_compilation_1-04b6d40.json
  tests/reference/asr-continue_compilation_1-04b6d40.stderr
Labels: intrinsic

#6037 fix : Handling ArrayItem in ArrayConstructor having Descriptor Array ttype
  integration_tests/CMakeLists.txt
  integration_tests/arrays_77.f90
  src/libasr/pass/implied_do_loops.cpp
Labels: PRIMA

#6043 fix: implementation of `dshiftr` for different kind value
  integration_tests/CMakeLists.txt
  integration_tests/test_dshiftr.f90
  src/libasr/pass/intrinsic_functions.h
Labels: intrinsic

#6048 fix: integration test runner
  integration_tests/run_tests.py
Labels: tests

#6054 fix: throw error for non-scalar in selected_int_kind, selected_real_kind, selected_char_kind
  src/lfortran/semantics/ast_common_visitor.h
  tests/errors/continue_compilation_1.f90
  tests/reference/asr-continue_compilation_1-04b6d40.json
  tests/reference/asr-continue_compilation_1-04b6d40.stderr
Labels: intrinsic

#6023 CI : Test `lincoa_example_2`
  .github/workflows/CI.yml
Labels: PRIMA

#6057 ci: test compilation of `lincoa_example_1.f90`
  .github/workflows/CI.yml
Labels: CI, PRIMA

#5940 fix: tokenizer errors generates ast and asr with cc flag - 2
  src/bin/lfortran.cpp
  src/lfortran/parser/fixedform_tokenizer.cpp
  src/lfortran/parser/fixedform_tokenizer.h
  src/lfortran/parser/parser.cpp
  src/lfortran/parser/parser.h
  src/lfortran/parser/parser.yy
  src/lfortran/parser/parser_exception.h
  src/lfortran/parser/tokenizer.h
  src/lfortran/parser/tokenizer.re
  tests/errors/continue_compilation_2.f90
  tests/reference/asr-continue_compilation_2-a6145a1.json
  tests/reference/asr-continue_compilation_2-a6145a1.stderr
Labels: error resiliency

#6083 rem: macro `transform_stmts_impl` from simplifier pass
  src/libasr/pass/simplifier.cpp
Labels: refactor, simplifier pass

#6104 ci: run `lincoa_2` only on Linux
  .github/workflows/CI.yml
Labels: CI, PRIMA

#6114 fix: Created temporary for scalar `ArrayItem` on rhs if common to lhs array
  integration_tests/arrays_69.f90
  integration_tests/arrays_70.f90
  src/libasr/pass/simplifier.cpp
Labels: PRIMA

#6128 CI: update PRIMA CI (Cleaning workarounds that are solved)
  .github/workflows/CI.yml
Labels: CI, PRIMA

#5880 [LLVM] Use LLVM backend to generate IR for GPU offloading
  .github/workflows/CI.yml
  integration_tests/CMakeLists.txt
  integration_tests/run_tests.py
  src/bin/lfortran.cpp
  src/lfortran/fortran_evaluator.cpp
  src/lfortran/fortran_evaluator.h
  src/libasr/codegen/asr_to_llvm.cpp
  src/libasr/codegen/asr_to_mlir.cpp
  src/libasr/codegen/asr_to_mlir.h
  src/libasr/codegen/evaluator.cpp
  src/libasr/codegen/evaluator.h
  src/libasr/pass/openmp.cpp
  tests/reference/pass_openmp-do_concurrent_01-2a6df8c.json
  tests/reference/pass_openmp-do_concurrent_01-2a6df8c.stdout
Labels: mlir

#6155 CI : `lincoa 2` correct output
  .github/workflows/CI.yml
Labels: PRIMA

#6154 fix: allocating to temporary created for spread intrinsic
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_350.f90
  src/libasr/pass/simplifier.cpp
Labels: PRIMA

#6156 fix : Handling Array Size in Function call in Pass array by data using Deep copy
  integration_tests/CMakeLists.txt
  integration_tests/arrays_08_size.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: PRIMA
