Repository lfortran/lfortran, pull requests merged in 2025-04, with the labels that each got.

#6988 fix: handle present in nested functions correctly
  integration_tests/CMakeLists.txt
  integration_tests/intrinsics_376.f90
  src/libasr/pass/nested_vars.cpp
  src/libasr/pass/transform_optional_argument_functions.cpp
Labels: stdlib

#7004 CI: setup CI for fortran-primes code
  .github/workflows/CI.yml
  src/libasr/pass/intrinsic_array_function_registry.h
Labels: CI

#7024 ci: bump to latest commit for stdlib test with less workarounds
  .github/workflows/CI.yml
Labels: CI, stdlib

#7075 ci: bump to latest commit for stdlib
  ci/test_third_party_codes.sh
Labels: CI, stdlib

#7079 fix: assign correct value for `is_iostat_eor` and `is_iostat_end`
  integration_tests/file_29.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: stdlib, I/O

#7080 fix: pass pointer for constant also in `file_write`
  integration_tests/file_28.f90
  src/libasr/codegen/asr_to_llvm.cpp
Labels: stdlib, I/O

#7042 Skip procedures while tokenizing if not used under contains
  src/lfortran/parser/fixedform_tokenizer.cpp
  src/lfortran/parser/parser_exception.h
  tests/errors/continue_compilation_ff_2.f
  tests/reference/asr-continue_compilation_ff_2-0d47e17.json
  tests/reference/asr-continue_compilation_ff_2-0d47e17.stderr
  tests/tests.toml
Labels: error resiliency
